############################################################################
# Contest 2026 team 345 ES8311 I2S Audio test utility
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = es8311_audio
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_345_ES8311_AUDIO)

MAINSRC   = es8311_audio_main.c
CSRCS     = velafit_pcm_stream.c

include $(APPDIR)/Application.mk
