############################################################################
# Contest 2026 team 345 MIPI DSI Display test utility
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = dsi_display
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_345_DSI_DISPLAY)

MAINSRC   = dsi_display_main.c

include $(APPDIR)/Application.mk
